version: "3"
services:
  orders:
    environment:
    - reschedule=on-node-failure
    - JAVA_OPTS=-Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC
      -Djava.security.egd=file:/dev/urandom
    image: index.docker.io/weaveworksdemos/orders:master-9bf0fee1
