version: "3"
services:
  catalogue-db:
    environment:
    - reschedule=on-node-failure
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_DATABASE=socksdb
    image: index.docker.io/weaveworksdemos/catalogue-db:master-93452255
    labels:
        prometheus.ignore: "true"
